apiVersion: v1
kind: Pod
metdata:
   name: voting-app-pod
   labels:
     name: voting-app-pod
     app: demo-voting-app

   containers:
     - name: voting-app
       image: dockersamples/examplevotingapp_vote
       ports:
         - containerPort: 80



